server:
  port: 9191 
  
# Application Name And Routing
spring:
  application:
    name: API_GATEWAY
  
  cloud:
    gateway:
      routes:
      - id: PRODUCT-MS
        uri: lb://PRODUCT-MS
        predicates:
          - Path=/product_ms/**
  
      - id: CATEGORY-MS
        uri: lb://CATEGORY-MS 
        predicates:
        - Path=/category_ms/** 
      
      
      - id: SUPPLIER-MS
        uri: lb://SUPPLIER-MS 
        predicates:
        - Path=/supplier_ms/** 
          
eureka:
  client:
    register-with-eureka: true # no need to write as in PRODUCT SUPPLIER AND CATEGORY not writted <used to tell where to registered this i.e in eureka server>
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost

        